spring:
  application:
    name: Limit service

  datasource:
    url: jdbc:postgresql://localhost:5434/limit_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  web:
    locale: en
    locale-resolver: fixed

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
app:
  time-zone: Asia/Almaty
  limit:
    default-sum: 1000.00
    default-currency: USD
  exchange-rate:
    provider: twelvedata   # stub | twelvedata
    twelvedata:
      base-url: https://api.twelvedata.com
      api-key: ${TWELVEDATA_API_KEY}
      connect-timeout: 5s
      read-timeout: 10s
      max-retries: 3
      retry-delay: 1s
      retry-multiplier: 2.0
      retry-max-delay: 10s